### ISSUE TITLE
"Board Index" navigation links near top of each page do not work

### ISSUE THREAD

**Issue by maltokyo** [bitnami/bitnami-docker-phpbb#68]
**Description**

At the top of PHPBB normally there is this navigation bar:

![image](https://user-images.githubusercontent.com/1388507/98462063-8806b100-21b1-11eb-9c24-340e5af7d433.png)

When you click on forums/posts to navigate into the various content of the board, it should dynamically update to show you where you currently are in relation to the top of the board, so that you can click on any depth to quickly move to anywhere in the structure between where you are now and the top page.  When diving into any content on the board, however, the link structure in this section does not work, and it looks always like this, with the deep links to each level of structure missing:

![image](https://user-images.githubusercontent.com/1388507/98462128-05322600-21b2-11eb-8c7a-fdcf1031f4a2.png)

(there should be links in between the `<  <`, to each level of the structure that I am in currently.

**Steps to reproduce the issue:**

1. Fresh install of Bitnami PHP BB Docker.  Already this issue occurs

**Describe the results you received:**

As above in the description, no links in the navigation structure.

**Describe the results you expected:**

Links in the `<  <` of the image above should show the navigation structure.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 41
  Running: 40
  Paused: 0
  Stopped: 1
 Images: 55
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-12-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.42GiB
 Name: ssd.stippy.com
 ID: PWIB:EVGU:2WVK:P5GS:I24S:5772:Q2H3:DM5I:2MER:G6HT:YQIU:ARHC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Debian machine

**Comment by carrodher** [comment]
I am trying to reproduce the issue using the latest image (`docker.io/bitnami/phpbb:3-debian-10`) but I am not able to, in this case, the different levels appear without issues:
 <img width="1220" alt="Screenshot 2020-11-09 at 14 49 21" src="https://user-images.githubusercontent.com/13216600/98549210-c4620c00-229a-11eb-96f2-47a920554131.png">

What version are you using? How are you deploying the image? I am using the _docker-compose.yaml_ present in the root of this repository, without any modification. Are you able to reproduce the issue by using this _docker-compose.yaml_?

**Comment by maltokyo** [comment]
Hi @carrodher yes, running with the following docker-compose.  But I noticed the images I used are not the same as yours.  Should I use `docker.io/bitnami/phpbb:3-debian-10` rather than `bitnami/phpbb:latest`?  What is the difference?

Do you think I can provide any logs etc which may help?

```
version: '2'
services:
  mysite_mariadb:
    container_name: mysite_mariadb
    image: 'bitnami/mariadb:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=<<<REMOVED>>>
      - MARIADB_USER=my_mysite
      - MARIADB_DATABASE=my_mysite
      - MARIADB_PASSWORD=<<<REMOVED>>>
    volumes:
      - 'mariadbdir:/bitnami'
  mysite_phpbb:
    container_name: mysite_phpbb
    image: 'bitnami/phpbb:latest'
    restart: unless-stopped
    environment:
      - MARIADB_HOST=mysite_mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=my_mysite
      - PHPBB_DATABASE_NAME=my_mysite
      - PHPBB_DATABASE_PASSWORD=<<<REMOVED>>>
      - ALLOW_EMPTY_PASSWORD=no
      - VIRTUAL_HOST=mysite.mypage.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=mysite.mypage.com
      - LETSENCRYPT_EMAIL=myemail@gmail.com
# commented out as I am behind reverseproxy which handles this
#    ports:
#      - '80:80'
#      - '443:443'
    volumes:
      - 'phpbbdir:/bitnami'
    depends_on:
      - mysite_mariadb

volumes:
  mariadbdir:
  phpbbdir:
```

**Comment by carrodher** [comment]
Both images should be the same, those are [rolling tags](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers) that are updated every day and all of them are pointing to the same image:
```console
$ docker images
REPOSITORY                                                 TAG                 IMAGE ID            CREATED             SIZE
bitnami/phpbb                                              3-debian-10         c0fe505d8ec1        19 hours ago        754MB
bitnami/phpbb                                              latest              c0fe505d8ec1        19 hours ago        754MB
```

You can use different rolling tags, see https://github.com/bitnami/bitnami-docker-phpbb#supported-tags-and-respective-dockerfile-links but those ones are updated on a daily basis. On the other hand, you can use an immutable tag (the ones with the `-rXX` suffix).

In that case, as the issue is not appearing in the most recent tags, probably was something fixed in the past, but probably you are using a cached image. Can you try removing the image and pulling it again? You can list the images on your system by running `docker images` and then remove the desired one by running `docker image rm IMAGE ID`. In the same way, you can use any other tag, as all of them are pointing to the same image and as it's a different tag, docker is going to pull it again.

**Comment by maltokyo** [comment]
Hi @carrodher 
I just did delete the old image as you suggested, but still get this:

![image](https://user-images.githubusercontent.com/1388507/99184722-4e9beb80-2745-11eb-8375-1a779d4ebefe.png)

Current image is this one, and there are no other bitnami/phpbb images on the machine:

```
root@ssd:~/docker-phpbb-bitnami# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
bitnami/phpbb                                 latest              56f5a9d0da6b        7 hours ago         754MB
```

**Comment by FraPazGal** [comment]
Hi @maltokyo,

Have you tried using another browser or disabling any element-blocking extensions you have installed? I used `bitnami/phpbb:latest` and it is displaying everything correctly:

![image](https://user-images.githubusercontent.com/26460210/99247914-ef52df80-2807-11eb-898a-bb908b573029.png)
